apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: infinityx-gateway
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/infinityx-gateway
        ports:
        - containerPort: 8080
